Declare __stdout as a weak symbol
TF-M redirects output to serial by declaring its own `FILE __stdout`
and `int fputc(int ch, FILE *f)` and disables Arm toolchain's default
versions of the two symbols using the flag `-nostdlib`. But if an
application or OS (e.g. Mbed OS) needs to link TF-M's platform
library while still using the Arm toolchain's standard libraries,
linking will fail:

  Error: L6200E: Symbol __stdout multiply defined

To address this, turn `__stdout` into be a weak symbol.